customhost = "employee.cajrukp7vf1n.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "chongxueming-employee"
customregion = "us-east-1"
